# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "The Wa Programming Language"
  homepage "https://github.com/wa-lang/wa"
  version "0.10.0"
  license "AGPL-3.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wa-lang/wa/releases/download/v0.10.0/wa_0.10.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a2334a5d9fd54c4455c06baa87dd19ec44baa5001ed1b7728eae66b7c6ea7afd"

      def install
        bin.install "wa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wa-lang/wa/releases/download/v0.10.0/wa_0.10.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c682daf08d3870ee3eedb7b521be2973d2644365e9a5268c2136d07d7f3f45e9"

      def install
        bin.install "wa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wa-lang/wa/releases/download/v0.10.0/wa_0.10.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "bbddce9be4f373e1e5bd9ce2919aa21d3d8c9d452261ba2b5da64c108d8e9948"

      def install
        bin.install "wa"
      end
    end
  end

  test do
    system "#{bin}/wa"
  end
end
