# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "The Wa Programming Language"
  homepage "https://github.com/wa-lang/wa"
  version "0.14.0"
  license "AGPL-3.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wa-lang/wa/releases/download/v0.14.0/wa_v0.14.0_darwin-amd64.zip", using: CurlDownloadStrategy
      sha256 "e6bd4e9594f658c5513b1032f24b5e1e6a35c8fba54407796e811c163682e417"

      def install
        bin.install "wa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wa-lang/wa/releases/download/v0.14.0/wa_v0.14.0_darwin-arm64.zip", using: CurlDownloadStrategy
      sha256 "7947a857e83accfdb54cb23ec6bf663355cd548f6777520ea3f3f2bb1f048945"

      def install
        bin.install "wa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wa-lang/wa/releases/download/v0.14.0/wa_v0.14.0_linux-amd64.zip", using: CurlDownloadStrategy
      sha256 "4fef36b9c858d2778e226a67435460c55c28521cd6611d8ad6932afe4f1447e2"

      def install
        bin.install "wa"
      end
    end
  end

  test do
    system "#{bin}/wa"
  end
end
